version: 2.1

orbs:
  ci-caching: jobcloud/ci-caching@3.1.1
  ci-php: jobcloud/ci-php@2.4.0

workflows:
  version: 2
  test-chubbyphp-socket-server-mock:
    jobs:
      - ci-caching/build-docker-images:
          context: dockerhub-credentials
      - ci-php/install-dependencies:
          context: dockerhub-credentials
          requires:
            - ci-caching/build-docker-images
      - ci-php/test:
          context: dockerhub-credentials
          requires:
            - ci-php/install-dependencies
      - ci-php/code-style:
          context: dockerhub-credentials
          requires:
            - ci-php/install-dependencies
      - ci-php/static-analysis:
          context: dockerhub-credentials
          requires:
            - ci-php/install-dependencies
      - ci-php/infection-testing:
          context: dockerhub-credentials
          requires:
            - ci-php/install-dependencies
