version: '3.2'

services:
  php:
    container_name: chubbyphp-socket-server-mock-php
    hostname: chubbyphp-socket-server-mock-php
    build:
      context: dev/php
      args:
        USER_ID: ${USER_ID}
    volumes:
      - ../:/var/www/html
    tty: true
